using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

public class BushBehav : MonoBehaviour
{
    [Header("Debug")]
    [SerializeField] private bool debugStealth = true;

    [Header("Player Bush Opacity")]
    [SerializeField, Range(0f, 1f)]
    private float hiddenOpacity = 0.5f;

    [Header("Bush Sound Effects")]
    [SerializeField] private AudioClip enterBushSound;
    [SerializeField] private AudioClip exitBushSound;
    [SerializeField, Range(0f, 1f)]
    private float bushSoundVolume = 1f;

    [Header("Bush Stealth")]
    [SerializeField] private int maxHiddenTurns = 3;

    [Header("Exhausted Bush")]
    [SerializeField, Range(0f, 1f)]
    private float exhaustedBushOpacity = 0.5f;

    private GridManager gridManager;
    private Vector2Int bushGridPosition;

    private bool wasHidden = false;

    // How many completed rounds this bush has provided stealth.
    private int hiddenTurns = 0;

    // Prevents this bush from being processed twice
    // during the same round.
    private int lastProcessedRound = -1;

    // Existing RoundManager event connection.
    // No public API changes.
    private RoundManager roundManager;
    private bool subscribedToRoundManager = false;


    // =========================================================
    // AWAKE
    // =========================================================

    private void Awake()
    {
        gridManager =
            FindFirstObjectByType<GridManager>();

        roundManager =
            FindFirstObjectByType<RoundManager>();
    }


    // =========================================================
    // ENABLE / DISABLE
    // =========================================================

    private void OnEnable()
    {
        SubscribeToRoundManager();
    }


    private void OnDisable()
    {
        UnsubscribeFromRoundManager();
    }


    // =========================================================
    // START
    // =========================================================

    private void Start()
    {
        RefreshBushGridPosition();

        // Safety in case RoundManager was not available
        // during OnEnable.
        SubscribeToRoundManager();
    }


    // =========================================================
    // UPDATE
    // =========================================================

    private void Update()
    {
        AttackUnit player =
            FindFirstObjectByType<AttackUnit>();

        if (player != null)
        {
            UpdatePlayerOpacity(
                player.gameObject
            );
        }
    }


    // =========================================================
    // ROUND MANAGER CONNECTION
    // =========================================================

    private void SubscribeToRoundManager()
    {
        if (subscribedToRoundManager)
        {
            return;
        }

        if (roundManager == null)
        {
            roundManager =
                FindFirstObjectByType<RoundManager>();
        }

        if (roundManager == null)
        {
            return;
        }

        roundManager.OnRoundChanged +=
            HandleRoundChanged;

        subscribedToRoundManager = true;
    }


    private void UnsubscribeFromRoundManager()
    {
        if (!subscribedToRoundManager)
        {
            return;
        }

        if (roundManager != null)
        {
            roundManager.OnRoundChanged -=
                HandleRoundChanged;
        }

        subscribedToRoundManager = false;
    }


    // =========================================================
    // ROUND CHANGED
    // =========================================================

    private void HandleRoundChanged(
        int newRound)
    {
        // Round 1 is generated by ResetRounds().
        //
        // Start a new encounter with fresh bushes.
        if (newRound == 1)
        {
            hiddenTurns = 0;
            lastProcessedRound = -1;
            wasHidden = false;

            RestoreBushOpacity();

            return;
        }


        // RoundManager increments currentRound AFTER
        // the previous round has completely finished.
        //
        // Example:
        //
        // Round 1 finishes
        // currentRound becomes 2
        //
        // Therefore:
        // completedRound = newRound - 1
        int completedRound =
            newRound - 1;


        // Already processed this round.
        if (lastProcessedRound == completedRound)
        {
            return;
        }

        lastProcessedRound =
            completedRound;


        AttackUnit player =
            FindFirstObjectByType<AttackUnit>();

        if (player == null)
        {
            return;
        }


        // The player must still be occupying this bush
        // when the round ends for this bush to consume
        // one stealth round.
        //
        // IMPORTANT:
        // Leaving the bush does NOT reset hiddenTurns.
        if (!IsPlayerOnBush(player))
        {
            return;
        }


        // Already exhausted.
        if (hiddenTurns >= maxHiddenTurns)
        {
            return;
        }


        hiddenTurns++;


        // =====================================================
        // BUSH EXHAUSTED
        // =====================================================

        if (hiddenTurns >= maxHiddenTurns)
        {
            SetExhaustedBushOpacity();
        }


        if (debugStealth)
        {
            Debug.Log(
                "[BushBehav] " +
                gameObject.name +
                " consumed stealth at end of Round " +
                completedRound +
                ". " +
                hiddenTurns +
                "/" +
                maxHiddenTurns,
                this
            );

            if (hiddenTurns >= maxHiddenTurns)
            {
                Debug.Log(
                    "[BushBehav] " +
                    gameObject.name +
                    " is now EXHAUSTED.",
                    this
                );
            }
        }
    }


    // =========================================================
    // GRID POSITION
    // =========================================================

    public void RefreshBushGridPosition()
    {
        if (gridManager == null)
        {
            gridManager =
                FindFirstObjectByType<GridManager>();
        }

        if (gridManager == null)
        {
            return;
        }

        bushGridPosition =
            gridManager.WorldToGridPosition(
                transform.position
            );
    }


    public Vector2Int GetBushGridPosition()
    {
        RefreshBushGridPosition();

        return bushGridPosition;
    }


    public bool IsPlayerOnBush(
        AttackUnit player)
    {
        if (player == null)
        {
            return false;
        }

        return player.GetCurrentGridPosition() ==
               GetBushGridPosition();
    }


    // =========================================================
    // PLAYER OPACITY
    // =========================================================

    private void UpdatePlayerOpacity(
        GameObject playerObject)
    {
        if (playerObject == null)
        {
            return;
        }

        AttackUnit player =
            playerObject.GetComponentInParent<AttackUnit>();

        if (player == null)
        {
            return;
        }

        bool hidden =
            IsHidden(playerObject);


        // =====================================================
        // ENTER / EXIT SOUND
        // =====================================================

        if (hidden != wasHidden)
        {
            if (hidden)
            {
                PlayBushSound(
                    enterBushSound
                );
            }
            else
            {
                PlayBushSound(
                    exitBushSound
                );
            }

            wasHidden = hidden;
        }


        // =====================================================
        // APPLY PLAYER OPACITY
        // =====================================================

        if (hidden)
        {
            BushBehav[] bushes =
                FindObjectsByType<BushBehav>(
                    FindObjectsSortMode.None
                );

            foreach (
                BushBehav bush
                in bushes
            )
            {
                if (bush == null)
                {
                    continue;
                }

                if (
                    player.GetCurrentGridPosition() ==
                    bush.GetBushGridPosition()
                )
                {
                    SetPlayerOpacity(
                        playerObject,
                        bush.hiddenOpacity
                    );

                    return;
                }
            }
        }


        // =====================================================
        // PLAYER VISIBLE
        // =====================================================

        SetPlayerOpacity(
            playerObject,
            1f
        );
    }


    // =========================================================
    // EXHAUSTED BUSH VISUAL
    // =========================================================

    private void SetExhaustedBushOpacity()
    {
        SpriteRenderer[] renderers =
            GetComponentsInChildren<SpriteRenderer>(
                true
            );

        foreach (
            SpriteRenderer spriteRenderer
            in renderers
        )
        {
            if (spriteRenderer == null)
            {
                continue;
            }

            Color color =
                spriteRenderer.color;

            color.a =
                exhaustedBushOpacity;

            spriteRenderer.color =
                color;
        }
    }


    // =========================================================
    // RESTORE BUSH VISUAL
    // =========================================================

    private void RestoreBushOpacity()
    {
        SpriteRenderer[] renderers =
            GetComponentsInChildren<SpriteRenderer>(
                true
            );

        foreach (
            SpriteRenderer spriteRenderer
            in renderers
        )
        {
            if (spriteRenderer == null)
            {
                continue;
            }

            Color color =
                spriteRenderer.color;

            color.a = 1f;

            spriteRenderer.color =
                color;
        }
    }


    // =========================================================
    // SOUND
    // =========================================================

    private void PlayBushSound(
        AudioClip clip)
    {
        if (clip == null)
        {
            return;
        }

        AudioSource.PlayClipAtPoint(
            clip,
            transform.position,
            bushSoundVolume
        );
    }


    // =========================================================
    // STATIC STEALTH CHECK
    // =========================================================

    public static bool IsHidden(
        GameObject playerObject)
    {
        if (playerObject == null)
        {
            return false;
        }

        AttackUnit player =
            playerObject.GetComponentInParent<AttackUnit>();

        if (player == null)
        {
            return false;
        }

        Vector2Int playerTile =
            player.GetCurrentGridPosition();

        BushBehav[] bushes =
            FindObjectsByType<BushBehav>(
                FindObjectsSortMode.None
            );

        foreach (
            BushBehav bush
            in bushes
        )
        {
            if (bush == null)
            {
                continue;
            }

            Vector2Int bushTile =
                bush.GetBushGridPosition();

            if (playerTile != bushTile)
            {
                continue;
            }


            // =================================================
            // BUSH STILL HAS STEALTH
            // =================================================

            if (
                bush.hiddenTurns <
                bush.maxHiddenTurns
            )
            {
                return true;
            }


            // =================================================
            // BUSH IS EXHAUSTED
            // =================================================

            return false;
        }

        return false;
    }


    // =========================================================
    // PLAYER SPRITE OPACITY
    // =========================================================

    private static void SetPlayerOpacity(
        GameObject playerObject,
        float opacity)
    {
        if (playerObject == null)
        {
            return;
        }

        SpriteRenderer[] renderers =
            playerObject.GetComponentsInChildren<SpriteRenderer>(
                true
            );

        foreach (
            SpriteRenderer spriteRenderer
            in renderers
        )
        {
            if (spriteRenderer == null)
            {
                continue;
            }

            Color color =
                spriteRenderer.color;

            color.a =
                opacity;

            spriteRenderer.color =
                color;
        }
    }
}